# Generated by Django 4.0.4 on 2022-05-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('training', 'training'), ('complete', 'complete')], max_length=255)),
                ('ml_model', models.CharField(choices=[('Decision Tree', 'Decision Tree'), ('Extra trees', 'Extra trees'), ('Random Forest', 'Random Forest'), ('HGB', 'HGB'), ('Cat Boost', 'Cat Boost'), ('GBM', 'GBM'), ('Light GBM', 'Light GBM'), ('Ada Boost', 'Ada Boost'), ('Super Vector Machine', 'Super Vector Machine'), ('SGD', 'SGD'), ('KNN', 'KNN')], max_length=255)),
                ('gender_choices', models.BooleanField()),
                ('region_choices', models.BooleanField()),
                ('rf_age', models.BooleanField()),
                ('rf_gender', models.BooleanField()),
                ('rf_bmi', models.BooleanField()),
                ('rf_children', models.BooleanField()),
                ('rf_is_smoker', models.BooleanField()),
                ('rf_region', models.BooleanField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
