# Generated by Django 4.0.4 on 2022-05-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained_ml', '0002_remove_modeltrainstatus_gender_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainstatus',
            name='create_date',
            field=models.TimeField(auto_now=True),
        ),
    ]
