# Generated by Django 4.0.4 on 2022-05-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained_ml', '0003_modeltrainstatus_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainstatus',
            name='create_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modeltrainstatus',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
