# Generated by Django 4.0.4 on 2022-05-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained_ml', '0004_modeltrainstatus_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltrainstatus',
            name='status',
            field=models.CharField(choices=[('training', 'training'), ('complete', 'complete')], default='training', max_length=255),
        ),
    ]
