# Generated by Django 4.0.4 on 2022-05-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trained_ml', '0005_alter_modeltrainstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltrainstatus',
            name='ml_model',
            field=models.CharField(choices=[('decisiontree', 'Decision Tree'), ('extratrees', 'Extra trees'), ('randomforest', 'Random Forest'), ('hgb', 'HGB'), ('catboost', 'Cat Boost'), ('gbm', 'GBM'), ('lightgbm', 'Light GBM'), ('adaboost', 'Ada Boost'), ('svm', 'Super Vector Machine'), ('sgd', 'SGD'), ('multilayerperceptron', 'Multi Layer Perceptron'), ('xgboost', 'Extreme Gradient Boost')], max_length=255),
        ),
        migrations.CreateModel(
            name='ModelInference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now=True)),
                ('create_time', models.TimeField(auto_now=True)),
                ('rf_age', models.BooleanField(default=False)),
                ('rf_gender', models.BooleanField(default=False)),
                ('rf_bmi', models.BooleanField(default=False)),
                ('rf_children', models.BooleanField(default=False)),
                ('rf_is_smoker', models.BooleanField(default=False)),
                ('rf_region', models.BooleanField(default=False)),
                ('result', models.DecimalField(decimal_places=2, max_digits=15)),
                ('on_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trained_ml.modeltrainstatus')),
            ],
        ),
    ]
